### PR TITLE
Updated to render correct ordinals in Download progress counts.

### PR DESCRIPTION
**Pull request by changeling**
fstogedcom.py:
Lines 34-45: Implemented ordinal() function.
Line 441: Yield correct ordinal for ancestor generations.
Line 450: Yield correct ordinal for descendant generations.

getmyancestors.py
Lines 107-118: Implemented ordinal() function.
Line: 960: Yield correct ordinal for ancestor generations.
Line 970: Yield correct ordinal for descendant generations.

translation.py
Lines 104-115: Translate ordinal suffixes.
Lines 116-120: Translate updated ancestor and descendant generation strings.

### CODE REVIEW

**Comment by Linekio** [comment]
It's a good idea, the problem is that it's not compatible with other languages. I put "th" in English and "e" in French because I'm lazy, but in French it's "1er, 2d, 3e ..." to the masculine gender and "1re, 2de, 3e .. to the feminine gender. (Here the sentence is feminine).
For example if I translate "st" by "re", it does not work because we must have 21e, 31e, etc ...

Maybe the solution is just to change the sentence ...

Another thing: your code does'nt work for 11, 12 and 13.

**Comment by changeling** [comment]
I assumed the 'e' was a placeholder, and was just addressing the english ordinals,, but it is a translation challenge. :/ I suppose the full sentences could implemented as the returned ordinal suffix, with corresponding translation entries. If you don't mind, I'll tinker with the approach.

Also, I've modified the pull request to correct the (dumb mistake on my part. I know better. :/) handling of 11, 12 and 13.

**Comment by changeling** [comment]
> I wonder if there is a multilingual library for ordinal numbers.
> Otherwise I guess I have to change the text.

Turns out there is (are). I've updated this to replace my ordinals() usage with the num2words module, which handles ordinals, translations and a few other transformations of numbers.

The French ordinal is still an issue regarding the masc/fem context, but this will at least render correct ordinals for languages aside from contextual issues.

**Comment by Linekio** [comment]
Well found this lib num2words!
The ordinal numbers are wrong in French but I guess I will make a pull request.
I will check your code later. Can you modify the README.md to note that num2words is necessary?

**Comment by Linekio** [comment]
https://github.com/savoirfairelinux/num2words/pull/232

**Comment by changeling** [comment]
I love the Open Source cascade of improvements:
num2words -> getmyancestors -> num2words. :)

I've pushed updates to README.md here. Removed the reference to linux in the module install lines, as this should apply to any platform.
Added num2words requirement.
Updated to reference the github repository for suggestions and bugs, and home of the project.

**Comment by changeling** [comment]
I noticed that the savoirfaire pull request tests failed. I haven't had time to look into why, but if I had to guess, I'd bet the actual test needs to be updated. Just thought I'd suggest that avenue:

https://github.com/Linekio/num2words/blob/french_ordinals/tests/test_fr.py

**Pull request merged**
