### PR TITLE
Update auth flow

### PR DESCRIPTION
**Pull request by adriaanjoubert**
#55

Based on https://github.com/jmichault/gramps-kromprogramoj/pull/25 and https://github.com/jmichault/gramps-kromprogramoj/pull/26

### CODE REVIEW

**Comment by Linekio** [comment]
Hello, what is the origin of this app key ? (client_id)

**Comment by adriaanjoubert** [comment]
> [jmichault/gramps-kromprogramoj](https://github.com/jmichault/gramps-kromprogramoj/pull/25)

I have no idea. I copied it from jmichault/gramps-kromprogramoj

**Comment by adriaanjoubert** [comment]
> Hello, what is the origin of this app key ? (client_id)

I have no idea. I copied it from jmichault/gramps-kromprogramoj

**Comment by Linekio** [comment]
I found this app key as an example in this page : https://www.familysearch.org/developers/docs/guides/authentication
So I'm very surprised that this key works and I guess it could be disable in the future.
However, it currently doesn't works for the ordinance route `/service/tree/tree-data/reservations/person/{fid}/ordinances`.
The current authenfication method works if not used too frequently. So I guess we can use this new auth method only if the '-c' option is not enabled.

**Comment by edcrfv0** [comment]
The connection logic and client_id seem to actually come from here: https://github.com/misbach/fs-auth

But it would be nice if it was possible to set the client_id as a command line argument. That way, one could try to use another client_id found for instance in one of the web apps listed here https://grms.my.site.com/solutionsgallery/ 😁

Some are supposed to work for ordinances as well, for instance [Eternal Reminder](https://grms.my.site.com/solutionsgallery/s/gallery-profile/a2R3Z00000LFsTcUAL/00864) (C59X-V65H-M57B-P1VM-KTZL-QW81-P4PR-WDP2), [Kinpoint](https://grms.my.site.com/solutionsgallery/s/gallery-profile/a2R3Z00000LcZovUAF/05275) (19ZF-9HZ8-T8WW-XS9P-1Z3W-JHK4-DLJV-CSMN) or [RootsFinder](https://grms.my.site.com/solutionsgallery/s/gallery-profile/a2R3Z00000LcZpAUAV/05278) (a02j000000MacanAAB) can supposedly support LDS Features... but I don't have a church account to test this...

**Comment by Linekio** [comment]
Changing only client_id doesn't works, you must also use the redirect_url configured for this client_id.

**Comment by edcrfv0** [comment]
Not sure it's the right place for putting this but here are a few client_id/redirect_uri I retrieved from that list:
|                                   | client_id                               | redirect_uri                                            | read information from your FamilySearch Account | update information into your FamilySearch Account | support LDS Features |
|-----------------------------------|-----------------------------------------|---------------------------------------------------------|-------------------------------------------------|---------------------------------------------------|----------------------|
| FamilySearch                      | 3Z3L-Z4GK-J7ZS-YT3Z-Q4KY-YN66-ZX5K-176R | https://www.familysearch.org/auth/familysearch/callback | x                                               | x                                                 | x                    |
| BYU Family History Technology Lab | TDBN-XQ3H-Y6VQ-WQLS-YWZN-QFP1-B9FP-4H96 | https://auth.fhtl.org/return                            | x                                               |                                                   |                      |
| EmulateMe                         | SFB4-1MW6-4YLK-PB6P-G3HT-8637-DPK9-MZJX | https://app.emulateme.ai/auth/fs/callback               | x                                               | x                                                 |                      |
| Eternal Reminder                  | C59X-V65H-M57B-P1VM-KTZL-QW81-P4PR-WDP2 | https://eternalreminder.org/new.php                     | x                                               |                                                   | x                    |
| Kinpoint                          | 19ZF-9HZ8-T8WW-XS9P-1Z3W-JHK4-DLJV-CSMN | https://kinpoint.com/server/fs/redirect                 | x                                               | x                                                 | x                    |
| Map My Cousins                    | a023Z00000ZrAyjQAF                      | https://cousinsclub.org/Maps/MMC.html?mtype=FS          | x                                               |                                                   |                      |
| MyFamilyArchive                   | a023Z00000ZsFUgQAN                      | https://collectionaire.com/oauth-redirect/callback      | x                                               |                                                   |                      |
| Patronomia                        | a02j000000KRPERAA5                      | https://fs.patronomia.com/app/oauthResponse/            | x                                               |                                                   |                      |
| Permanent.org                     | a023Z00000T8LHQQA3                      | https://www.permanent.org/app/apps                      | x                                               | x                                                 |                      |
| Puzzilla                          | 3VRL-L4MW-59J5-Q7TT-Z416-Q65B-DDVM-L341 | https://puzzilla.org/descendants                        | x                                               |                                                   | x                    |
| RootsFinder                       | a02j000000MacanAAB                      | https://www.rootsfinder.com/auth/familysearch           | x                                               | x                                                 | x                    |
| RootsMapper                       | WNWM-GWPH-WRHW-T133-KN57-88S6-JKL4-DL3G | https://rootsmapper.com                                 | x                                               |                                                   |                      |
| GenealogyWallCharts               | HP2M-83C1-5GKS-9YJW-GD47-1193-QW7P-XHQC | https://www.genealogywallcharts.com/fs-callback.htm     |                                                 |                                                   |                      |

**Comment by Linekio** [comment]
I finally merge with the patch from https://github.com/Linekio/getmyancestors/issues/55

**Pull request merged**
