### PR TITLE
Update GEDCOM Header in getmyancestors.py for 5.5.1 compliance.

### PR DESCRIPTION
**Pull request by changeling**
getmyancestors.py: Add SOUR, SUBM ref and SUBM entry. Update VERS to 5.5.1.
(UTF-8 is only in GEDCOM 5.5.1 and not 5.5, but getmyancestors creates header with VERS 5.5 and encoding UTF-8. `.ged` files created appear otherwise to be 5.5.1.)

### CODE REVIEW

**Comment by Linekio** [comment]
You're right about VERS, and some tags only exist in version 5.5.1, (MAP, LATI and LONG).
I guess "SOUR" should contain "getmyancestors", and "SUBM" should contain the user's informations (available in https://www.familysearch.org/platform/users/current.json).
What is your opinion ?

**Comment by changeling** [comment]
I think you're absolutely right. I've now added several tags to the HEAD and updated the SUBM from available values. I'm not sure how or if you're currently versioning the project, so I put a placeholder in the VERS tag.

I also added DATE and TIME to HEAD using the time at file creation.

I put `getmyancestors` in the SOUR, SOUR.NAME and DEST tags, as discussed here:
https://www.tamurajones.net/GEDCOMSOURandDEST.xhtml.

Also, I'm using the annotated 5.5.1 from Tamura Jones for supplemental research. I'll attach it here in case you haven't seen it.

[TFG551SAERev1.zip](https://github.com/Linekio/getmyancestors/files/2735992/TFG551SAERev1.zip)

The language code from current.json (2 chars) is not legal GEDCOM, so I've added the babelfish python module to handle converting to full language name, and updated the README.md to include that module.

I hope you don't mind my taking liberties here. This is such a good project.

**Comment by changeling** [comment]
I've gone ahead and put these changes into a PR. Let me know how it looks.

**Comment by Linekio** [comment]
Here the smallest gedcom file: https://www.tamurajones.net/downloads/SmallestGEDCOM/Smallest.ged
So I think lines 886 to 888 are useless:
```
        file.write('2 VERS 1.0placeholder\n')
        file.write('2 NAME getmyancestors\n')
        file.write('1 DEST getmyancestors\n')
```

**Comment by changeling** [comment]
The HEAD.SOUR.VERS, ...NAME, and ...DEST elements identify the specific 'dialect' of a given file. That is, what quirks or variations a specific file may have, to be used by software reading that file to special-case the import for that file's dialect.

In this case, another developer could see that this file came from `getmyancestors`, version `1.0placeholder` (not a real, or good, version number. just my placeholder.), and create an import routine specifically for `getmyancestors` files.

There's a good discussion , particularly the "usage" and "HEAD.DEST" sections, in https://www.tamurajones.net/GEDCOMSOURandDEST.xhtml

So, with:

    1 SOUR getmyancestors
    2 VERS 1.0placeholder
    2 NAME getmyancestors
    1 DEST getmyancestors

`getmyancestors` is, in essence, being a good citizen by identifying these elements. In the real world, as an example, as `mergemyancestors.py` is designed to work with files generated by `getmyancestors`, this structure offers you the ability to actually check, and warn the user if the files aren't from `getmyancestors`, and state that the results may not be as expected.

Also, as `getmyancestors` evolves, `mergemyancestors` and other potential programs, can recognize that a file generated by `0.1.99` differs from one generated by `1.2`, and anticipate the differences.

Regarding the `1.0placeholder` version: this should be whatever version system you decide to use for `getmyancestors`, if you decide to, though something like major.minor.revision.build is presented in Tamura Jones' annotated 5.5.1 (attached in my previous message). Search for "GEDCOM version best practice", on page 129.

**Comment by Linekio** [comment]
Add a check in mergemyancestors is a good id, but it should be based SOUR, not DEST.
DEST assumes that the file is written for a specific software. That's not the case, I'm just aiming for compatibility with as much software as possible.
mergemyancestors is never a destination soft, it's a tool related to getmyancestors.

- Please remove DEST tag,
- Change VERS  to "1.0"
- Rebase your branch and solve conflicts

About NAME, perhaps it would be useful to differentiate between CLI and UI versions.

Thanks for your contribution.

**Comment by changeling** [comment]
I've made these changes.

On the NAME question, that depends, I'd think, on whether the GEDCOM generated by one differs from the other. If they are identical, then there's no need for anything other than historical reference. 
For distinguishing dialects, it's likely unnecessary.

On the other hand, I guess there's no harm in doing so.

**Pull request merged**
